name: "Protocol Buffer Go Stubs Generation"
on:
    push:
        branches:
            - '*'
jobs:
    protoc:
        name: "Generate"
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.23
            - uses: actions/checkout@v2
            - name: "Generate for Golang"
              run: |
                sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
                go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
                go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
                mkdir go
                cd go                
                protoc --go_out=./go --go_opt=paths=source_relative --go-grpc_out=./go --go-grpc_opt=paths=source_relative ./**/*.proto
                go mod init github.com/bochap-learning/manning-grpc-microservices-proto
                go mod tidy
                git config --global user.email "moibochap@gmail.com"
                git config --global user.name "bochap"
                git add .
                git commit -am "proto update"
                git push origin main